### ISSUE TITLE
Config explanation

### ISSUE THREAD

**Issue by binooetomo** [LampAndMaxAxie/LampAndMaxAxieBot#1]
Dear Sir.

I applogize to use this issue to contact you.
I tried to add you as discord friend, but MaikeruKonare#3141 didn't work.
(BTW, my discord is bino#2378)

Is there any documentation about config.cfg?
I'm confuse about : 
1. alertsChannelId, leaderboardsChannelId :  What is it's purpose? when it used? what kind of message will the bot send to that channel?

2. leaderboardsPeriodHours : what is it?

Sincerely

-bino-

**Comment by maconard** [comment]
Sorry I didn't spot this! Our primary communication is through our Discord server. I will close this issue and reach out to you on Discord.
